Repository nimblehq/android-templates, pull requests merged in 2021-04, with the labels that each got.

#69 [CHORE] Add Github CODEOWNERS config: auto-request all members for code review
  .github/CODEOWNERS
Labels: type : chore

#72 [Chucker Interceptor] Add Chucker Interceptor to snap the API response
  RxJavaTemplate/app/build.gradle
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/OkHttpClientModule.kt
  RxJavaTemplate/build.gradle
Labels: type : feature

#66 [Support Edge to edge] 1/2 - Update more edge to edge ui usecases
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/extension/WebViewExt.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseViewModel.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/NavigationEvent.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/common/ItemClickable.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/MainNavigator.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/DataAdapter.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeViewModel.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondViewModel.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/AppWebChromeClient.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewBundle.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewViewModel.kt
  RxJavaTemplate/app/src/main/res/layout/fragment_main.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_second.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_webview.xml
  RxJavaTemplate/app/src/main/res/layout/item_data.xml
  RxJavaTemplate/app/src/main/res/layout/view_loading.xml
  RxJavaTemplate/app/src/main/res/navigation/nav_graph_main.xml
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/MainNavigatorTest.kt
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/data/DataTest.kt
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/home/HomeViewModelTest.kt
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/second/SecondViewModelTest.kt
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/webview/WebViewViewModelTest.kt
  RxJavaTemplate/data/src/main/java/co/nimblehq/rxjava/data/service/response/ExampleApiResponse.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/data/Data.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/repository/ApiRepository.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/test/MockUtil.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/usecase/GetExampleDataUseCase.kt
  RxJavaTemplate/domain/src/test/java/co/nimblehq/rxjava/domain/usecase/GetExampleDataUseCaseTest.kt
Labels: type : chore

#67 [Support Edge to edge] 2/2 - Integrate edge to edge support helper
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/base/BaseFragmentCallbacks.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/helpers/SupportEdge2EdgeHelper.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewFragment.kt
  RxJavaTemplate/app/src/main/res/layout/activity_main.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_home.xml
  RxJavaTemplate/app/src/main/res/navigation/nav_graph_main.xml
  RxJavaTemplate/app/src/main/res/values-v23/colors.xml
  RxJavaTemplate/app/src/main/res/values-v26/colors.xml
  RxJavaTemplate/app/src/main/res/values/colors.xml
  RxJavaTemplate/app/src/main/res/values/styles.xml
  RxJavaTemplate/build.gradle
Labels: type : feature

#75 Update github action with working_directory instead of cd
  .github/workflows/lint_and_unit_test.yml
Labels: priority : normal, type : chore
