Repository nimblehq/android-templates, pull requests merged in 2021-11, with the labels that each got.

#141 [Chore] Update Github reviewer list
  .github/CODEOWNERS
Labels: type : chore

#142 [chore] Bump version to 3.3.0
  CoroutineTemplate/build.gradle
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#143 [chore] Adjust code format
  RxJavaTemplate/app/src/main/res/font/font_circular_family.xml
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#138 [#111] Gradle scripts with Kotlin DSL - Part 2 (Coroutine Template)
  CoroutineTemplate/app/build.gradle
  CoroutineTemplate/app/build.gradle.kts
  CoroutineTemplate/app/proguard-rules.pro
  CoroutineTemplate/build.gradle
  CoroutineTemplate/build.gradle.kts
  CoroutineTemplate/buildSrc/build.gradle.kts
  CoroutineTemplate/buildSrc/src/main/java/Configurations.kt
  CoroutineTemplate/buildSrc/src/main/java/FileExt.kt
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  CoroutineTemplate/data/build.gradle
  CoroutineTemplate/data/build.gradle.kts
  CoroutineTemplate/data/proguard-rules.pro
  CoroutineTemplate/domain/build.gradle.kts
  CoroutineTemplate/settings.gradle
  CoroutineTemplate/settings.gradle.kts
Labels: type : feature

#139 [#83] Setup the unit testing part for Coroutine Template
  CoroutineTemplate/app/build.gradle.kts
  CoroutineTemplate/app/src/debug/AndroidManifest.xml
  CoroutineTemplate/app/src/debug/java/co/nimblehq/coroutine/EmptyHiltActivity.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/extension/ViewModelExt.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/test/TestModules.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/test/ViewModelExt.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/BaseFragmentTest.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/screens/home/HomeFragmentTest.kt
  CoroutineTemplate/app/src/test/resources/robolectric.properties
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#145 [111] Gradle scripts with Kotlin DSL - Part 3 (Jacoco and Checkstyle gradle)
  RxJavaTemplate/app/build.gradle.kts
  RxJavaTemplate/app/codequality.gradle
  RxJavaTemplate/app/codequality.gradle.kts
  RxJavaTemplate/config/jacoco.gradle
  RxJavaTemplate/config/jacoco.gradle.kts
  RxJavaTemplate/data/build.gradle.kts
  RxJavaTemplate/domain/build.gradle.kts
Labels: type : feature

#144 [#124] Update GitHub Action workflows to follow team convention
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
Labels: type : chore

#147 [Release] 3.3.0
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/CODEOWNERS
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  CoroutineTemplate/app/build.gradle
  CoroutineTemplate/app/build.gradle.kts
  CoroutineTemplate/app/proguard-rules.pro
  CoroutineTemplate/app/src/debug/AndroidManifest.xml
  CoroutineTemplate/app/src/debug/java/co/nimblehq/coroutine/EmptyHiltActivity.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/extension/ViewModelExt.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/test/TestModules.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/test/ViewModelExt.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/BaseFragmentTest.kt
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/screens/home/HomeFragmentTest.kt
  CoroutineTemplate/app/src/test/resources/robolectric.properties
  CoroutineTemplate/build.gradle
  CoroutineTemplate/build.gradle.kts
  CoroutineTemplate/buildSrc/build.gradle.kts
  CoroutineTemplate/buildSrc/src/main/java/Configurations.kt
  CoroutineTemplate/buildSrc/src/main/java/FileExt.kt
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  CoroutineTemplate/data/build.gradle
  CoroutineTemplate/data/build.gradle.kts
  CoroutineTemplate/data/proguard-rules.pro
  CoroutineTemplate/domain/build.gradle.kts
  CoroutineTemplate/settings.gradle
  CoroutineTemplate/settings.gradle.kts
  RxJavaTemplate/app/build.gradle.kts
  RxJavaTemplate/app/codequality.gradle
  RxJavaTemplate/app/codequality.gradle.kts
  RxJavaTemplate/app/src/main/res/font/font_circular_family.xml
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
  RxJavaTemplate/config/jacoco.gradle
  RxJavaTemplate/config/jacoco.gradle.kts
  RxJavaTemplate/data/build.gradle.kts
  RxJavaTemplate/domain/build.gradle.kts
Labels: type : release
