Repository nimblehq/android-templates, pull requests merged in 2021-07, with the labels that each got.

#80 Add UI tests to RxJavaTemplate
  RxJavaTemplate/app/build.gradle
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/TestRunner.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/di/modules/TestRepositoryModule.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/repository/TestApiRepositoryImpl.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/common/TestUtil.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/flow/AppFlowTest.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/screens/home/Home.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/screens/home/HomeFragmentTest.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/screens/second/Second.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/screens/second/SecondFragmentTest.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/screens/webview/WebView.kt
  RxJavaTemplate/app/src/androidTest/java/co/nimblehq/rxjava/ui/screens/webview/WebViewFragmentTest.kt
  RxJavaTemplate/app/src/debug/AndroidManifest.xml
  RxJavaTemplate/app/src/debug/java/co/nimblehq/rxjava/EmptyHiltActivity.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/AppModule.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/MoshiModule.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/OkHttpClientModule.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/RepositoryModule.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/RetrofitModule.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/StorageModule.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/MainNavigator.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/MainViewModel.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeFragment.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/home/HomeViewModel.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/second/SecondViewModel.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/ui/screens/webview/WebViewViewModel.kt
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/second/SecondViewModelTest.kt
  RxJavaTemplate/build.gradle
  RxJavaTemplate/data/build.gradle
  RxJavaTemplate/domain/build.gradle
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/test/MockUtil.kt
Labels: type : chore

#108 Setup Jetpack Compose (CoroutineTemplate) [Part1/2]
  CoroutineTemplate/app/build.gradle
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
  CoroutineTemplate/app/src/main/res/layout/fragment_home.xml
  CoroutineTemplate/build.gradle
  CoroutineTemplate/domain/build.gradle
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/data/entity/UserEntity.kt
  CoroutineTemplate/gradle/wrapper/gradle-wrapper.properties
Labels: type : feature

#106 [#105] Update Mockito library to fix some unit tests fail issues for RxJavaTemplate
  RxJavaTemplate/app/build.gradle
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/MainNavigatorTest.kt
  RxJavaTemplate/app/src/test/java/co/nimblehq/rxjava/ui/screens/home/HomeViewModelTest.kt
  RxJavaTemplate/build.gradle
  RxJavaTemplate/data/build.gradle
  RxJavaTemplate/domain/build.gradle
Labels: priority : low, type : chore

#110 Bump version to 3.1.0 and update gradle version
  RxJavaTemplate/build.gradle
  RxJavaTemplate/gradle/wrapper/gradle-wrapper.properties
Labels: type : chore
