Repository nimblehq/android-templates, pull requests merged in 2021-06, with the labels that each got.

#79 [View Binding] Migrate CoroutineTemplate UIs to view binding
  CoroutineTemplate/app/build.gradle
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseActivity.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseNavigator.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/MainActivity.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/MainNavigator.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondBundle.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondFragment.kt
Labels: type : feature

#76 Add github action template
  .cicdtemplate/.github/CODEOWNERS
  .cicdtemplate/.github/ISSUE_TEMPLATE/bug_template.md
  .cicdtemplate/.github/ISSUE_TEMPLATE/feature_template.md
  .cicdtemplate/.github/PULL_REQUEST_TEMPLATE.md
  .cicdtemplate/.github/README.md
  .cicdtemplate/.github/workflows/deploy_staging_and_production.yml
  .cicdtemplate/.github/workflows/test.yml
Labels: priority : normal, type : feature

#97 [96] Update .github template
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type : chore

#78 Set up network layer with Hilt
  CoroutineTemplate/app/build.gradle
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/TemplateApplication.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/DispatcherModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/MoshiModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/OkHttpClientModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/RepositoryModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/RetrofitModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/lib/Event.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeViewModel.kt
  CoroutineTemplate/build.gradle
  CoroutineTemplate/data/.gitignore
  CoroutineTemplate/data/build.gradle
  CoroutineTemplate/data/proguard-rules.pro
  CoroutineTemplate/data/src/main/AndroidManifest.xml
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/ApiService.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/providers/ApiServiceProvider.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/providers/ConverterFactoryProvider.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/providers/MoshiBuilderProvider.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/providers/RetrofitProvider.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/response/UserResponse.kt
  CoroutineTemplate/domain/.gitignore
  CoroutineTemplate/domain/build.gradle
  CoroutineTemplate/domain/proguard-rules.pro
  CoroutineTemplate/domain/src/main/AndroidManifest.xml
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/data/entity/UserEntity.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/dispatcher/DispatcherQualifiers.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/repository/UserRepository.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/usecase/GetUsersUseCase.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/usecase/UseCaseResult.kt
  CoroutineTemplate/settings.gradle
Labels: type : chore

#99 [81] Setup init template script
  .github/ISSUE_TEMPLATE.md
  CoroutineTemplate/app/src/main/AndroidManifest.xml
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/CoroutineTemplateApplication.kt
  README.md
  RxJavaTemplate/app/src/main/AndroidManifest.xml
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/RxJavaTemplateApplication.kt
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/AppModule.kt
  newproject.sh
Labels: type : chore

#101 [98] Add BaseSharedPreferences for RxJavaTemplate
  RxJavaTemplate/app/src/main/java/co/nimblehq/rxjava/di/modules/StorageModule.kt
  RxJavaTemplate/build.gradle
  RxJavaTemplate/domain/build.gradle
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/extension/SharePreferencesExt.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/storage/BaseSharedPreferences.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/storage/EncryptedSharedPreferences.kt
  RxJavaTemplate/domain/src/main/java/co/nimblehq/rxjava/domain/storage/NormalSharedPreferences.kt
Labels: priority : normal
