Repository nimblehq/android-templates, pull requests merged in 2022-09, with the labels that each got.

#295 [#266] Update description of pull request template
  .cicdtemplate/.github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type : chore, status : essential, priority : normal

#296 [Chore] Bump version to 3.12.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  template/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#291 [#213] [1/2 - Template] Apply to use Flow + get rid of custom UseCaseResult
  template/app/src/main/java/co/nimblehq/template/ui/screens/compose/HomeComposeViewModel.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/xml/HomeViewModel.kt
  template/data/build.gradle.kts
  template/data/src/main/java/co/nimblehq/template/data/repository/RepositoryImpl.kt
  template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
  template/domain/build.gradle.kts
  template/domain/src/main/java/co/nimblehq/template/domain/repository/Repository.kt
  template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCase.kt
  template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCaseResult.kt
  template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
Labels: type : feature

#306 [#304] Fix failing instrumentation tests
  template/buildSrc/src/main/java/Versions.kt
Labels: type : bug, status : essential, priority : high

#310 [#280] Update README to have license and about section
  README.md
  sample-compose/README.md
  sample-xml/README.md
Labels: type : chore

#309 [#264] Add version for new_project.kts to a properties file
  scripts/new_project.kts
  version.properties
Labels: type : feature, status : essential, priority : normal

#292 [#213] [2/2 - Sample] Apply to use Flow for Compose and XML samples
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/data/build.gradle.kts
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/RepositoryImpl.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/repository/RepositoryTest.kt
  sample-compose/domain/build.gradle.kts
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/repository/Repository.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCase.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCaseResult.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/data/build.gradle.kts
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/repository/RepositoryImpl.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/repository/RepositoryTest.kt
  sample-xml/domain/build.gradle.kts
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/repository/Repository.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCase.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCaseResult.kt
  sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
  template/data/src/main/java/co/nimblehq/template/data/repository/RepositoryImpl.kt
  template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
Labels: type : feature

#312 Release/3.12.0
  .cicdtemplate/.github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  sample-compose/README.md
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/RepositoryImpl.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/repository/RepositoryTest.kt
  sample-compose/domain/build.gradle.kts
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/repository/Repository.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCase.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCaseResult.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
  sample-xml/README.md
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/data/build.gradle.kts
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/repository/RepositoryImpl.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/repository/RepositoryTest.kt
  sample-xml/domain/build.gradle.kts
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/repository/Repository.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCase.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCaseResult.kt
  sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
  scripts/new_project.kts
  template/app/src/main/java/co/nimblehq/template/ui/ErrorMapping.kt
  template/app/src/main/java/co/nimblehq/template/ui/base/BaseComposeFragment.kt
  template/app/src/main/java/co/nimblehq/template/ui/base/BaseViewModel.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/compose/HomeComposeFragment.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/compose/HomeComposeViewModel.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/xml/HomeFragment.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/xml/HomeViewModel.kt
  template/buildSrc/src/main/java/Versions.kt
  template/data/build.gradle.kts
  template/data/src/main/java/co/nimblehq/template/data/extensions/ResponseMapping.kt
  template/data/src/main/java/co/nimblehq/template/data/repository/RepositoryImpl.kt
  template/data/src/main/java/co/nimblehq/template/data/response/ErrorResponse.kt
  template/data/src/test/java/co/nimblehq/template/data/extensions/ResponseMappingTest.kt
  template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
  template/data/src/test/java/co/nimblehq/template/data/test/MockUtil.kt
  template/domain/build.gradle.kts
  template/domain/src/main/java/co/nimblehq/template/domain/exceptions/Exceptions.kt
  template/domain/src/main/java/co/nimblehq/template/domain/model/Error.kt
  template/domain/src/main/java/co/nimblehq/template/domain/repository/Repository.kt
  template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCase.kt
  template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCaseResult.kt
  template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
  version.properties
Labels: type : release
