Repository nimblehq/android-templates, pull requests merged in 2022-10, with the labels that each got.

#313 [Chore] Update versions
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  template/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#316 [#267] Update issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/rfc_template.md
  .github/ISSUE_TEMPLATE/story_template.md
Labels: type : chore, status : essential, priority : normal

#321 [#262] Update use case to use operator invoke function instead of old…
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCase.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCase.kt
  sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/compose/HomeComposeViewModel.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/xml/HomeViewModel.kt
  template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCase.kt
  template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
Labels: type : chore, status : essential, priority : normal

#315 [#212] [2/2 - Sample] Add flowTransform to map and handle custom errors as Flow in data layer
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/ErrorMapping.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/extensions/ResponseMapping.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/RepositoryImpl.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/response/ErrorResponse.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/extensions/ResponseMappingTest.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/test/MockUtil.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/exceptions/Exceptions.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/model/Error.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/ErrorMapping.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/base/BaseViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragment.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/extensions/ResponseMapping.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/repository/RepositoryImpl.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/response/ErrorResponse.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/extensions/ResponseMappingTest.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/test/MockUtil.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/exceptions/Exceptions.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/model/Error.kt
Labels: type : feature, status : essential, priority : normal

#329 [#307] Update README for more clear about where should run the script
  README.md
Labels: type : bug, status : essential, priority : low

#331 [#294] Add Chucker library
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/OkHttpClientModule.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/app/build.gradle.kts
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/di/modules/OkHttpClientModule.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  template/app/build.gradle.kts
  template/app/src/main/java/co/nimblehq/template/di/modules/OkHttpClientModule.kt
  template/buildSrc/src/main/java/Versions.kt
Labels: type : feature, status : essential, priority : normal

#324 [#261] Add permission request handler
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/AndroidManifest.xml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeFragment.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/app/build.gradle.kts
  sample-xml/app/src/main/AndroidManifest.xml
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragment.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  template/app/build.gradle.kts
  template/buildSrc/src/main/java/Versions.kt
Labels: type : feature, status : essential, priority : normal

#330 [#230] Update publish_docs_to_wiki workflow to use publish_wiki of github_action_workflow repository
  .github/wiki/Home.md
  .github/workflows/publish_docs_to_wiki.yml
Labels: type : chore, status : essential, priority : normal

#339 [#265] Add dependency versions for workflows to a properties file
  .github/workflows/draft-new-release.yml
  .github/workflows/verify_newproject_script.yml
  README.md
  version.properties
Labels: type : chore, status : essential, priority : normal

#340 [Release] 3.13.0
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/rfc_template.md
  .github/ISSUE_TEMPLATE/story_template.md
  .github/wiki/Home.md
  .github/workflows/draft-new-release.yml
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/verify_newproject_script.yml
  README.md
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/AndroidManifest.xml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/OkHttpClientModule.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/ErrorMapping.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/extensions/ResponseMapping.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/RepositoryImpl.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/response/ErrorResponse.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/extensions/ResponseMappingTest.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/test/MockUtil.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/exceptions/Exceptions.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/model/Error.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UseCase.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
  sample-xml/app/build.gradle.kts
  sample-xml/app/src/main/AndroidManifest.xml
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/di/modules/OkHttpClientModule.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/ErrorMapping.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/base/BaseViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragment.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/extensions/ResponseMapping.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/repository/RepositoryImpl.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/response/ErrorResponse.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/extensions/ResponseMappingTest.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/test/MockUtil.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/exceptions/Exceptions.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/model/Error.kt
  sample-xml/domain/src/main/java/co/nimblehq/sample/xml/domain/usecase/UseCase.kt
  sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
  template/app/build.gradle.kts
  template/app/src/main/java/co/nimblehq/template/di/modules/OkHttpClientModule.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/compose/HomeComposeViewModel.kt
  template/app/src/main/java/co/nimblehq/template/ui/screens/xml/HomeViewModel.kt
  template/buildSrc/src/main/java/Versions.kt
  template/domain/src/main/java/co/nimblehq/template/domain/usecase/UseCase.kt
  template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
  version.properties
Labels: type : release

#341 [Chore] Bump version to 3.14.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore, priority : normal
