Repository nimblehq/android-templates, pull requests merged in 2022-03, with the labels that each got.

#161 [Chore] Bump version to 3.6.0
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#153 [#121] Update wiki-content for essential, optional and rejected features
  docs/Home.md
Labels: type : chore

#166 [#165] Fix Github Actions error
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/run_detekt_and_unit_tests.yml
Labels: type : bug

#162 [#155] Replace `jCenter()` with `mavenCentral()`
  RxJavaTemplate/build.gradle.kts
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#167 [CHORE] Add missing members to CODEOWNERS
  .github/CODEOWNERS
Labels: type : chore

#174 [CHORE] Update the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore

#164 [#157] Resolve resource warnings from Danger
  CoroutineTemplate/app/src/main/res/layout/fragment_home.xml
  RxJavaTemplate/app/src/main/res/font/font_circular_family.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_home.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_second.xml
  RxJavaTemplate/app/src/main/res/layout/item_data.xml
  RxJavaTemplate/app/src/main/res/values/colors_pallete.xml
  RxJavaTemplate/app/src/main/res/values/widget_styles.xml
  RxJavaTemplate/app/src/staging/res/values/strings_url.xml
Labels: type : chore

#176 [Release] 3.6.0
  .github/CODEOWNERS
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  CoroutineTemplate/app/src/main/res/layout/fragment_home.xml
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  Gemfile.lock
  RxJavaTemplate/app/src/main/res/font/font_circular_family.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_home.xml
  RxJavaTemplate/app/src/main/res/layout/fragment_second.xml
  RxJavaTemplate/app/src/main/res/layout/item_data.xml
  RxJavaTemplate/app/src/main/res/values/colors_pallete.xml
  RxJavaTemplate/app/src/main/res/values/widget_styles.xml
  RxJavaTemplate/app/src/staging/res/values/strings_url.xml
  RxJavaTemplate/build.gradle.kts
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
  docs/Home.md
Labels: type : release
