Repository nimblehq/android-templates, pull requests merged in 2022-12, with the labels that each got.

#359 [Chore] Bump version to 3.15.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore, priority : normal

#365 [#364] Migrate workflows setup-ruby action
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .github/workflows/review_pull_request.yml
Labels: type : bug, status : essential, priority : high

#366 [#170] Fix remaning warnings from danger
  template-compose/app/src/main/res/drawable/ic_launcher_foreground.xml
  template-xml/app/src/main/res/drawable/ic_launcher_foreground.xml
Labels: type : chore, status : essential, priority : normal

#368 [#361] Update new_project.kts to keep application name as is
  sample-compose/app/src/main/AndroidManifest.xml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/MainApplication.kt
  sample-xml/app/src/main/AndroidManifest.xml
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/MainApplication.kt
  scripts/new_project.kts
  template-compose/app/src/main/AndroidManifest.xml
  template-compose/app/src/main/java/co/nimblehq/template/compose/MainApplication.kt
  template-xml/app/src/main/AndroidManifest.xml
  template-xml/app/src/main/java/co/nimblehq/template/xml/MainApplication.kt
Labels: type : chore, status : essential, priority : normal

#371 [#369] Update deprecated Detekt attrs in all templates
  sample-compose/detekt-config.yml
  sample-xml/detekt-config.yml
  template-compose/detekt-config.yml
  template-xml/detekt-config.yml
Labels: type : chore, status : essential, priority : normal

#367 [#352] [Sample] 1/2: Setup the nav graph and navigation logic
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/debug/AndroidManifest.xml
  sample-compose/app/src/debug/java/co/nimblehq/sample/compose/EmptyHiltActivity.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/NavigatorModule.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extension/ViewModelExt.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppDestination.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppNavigation.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseActivity.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseComposeFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseComposeFragmentCallbacks.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseNavigator.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/NavigationEvent.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/NavigationException.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/MainActivity.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/MainNavigator.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Theme.kt
  sample-compose/app/src/main/res/layout/activity_main.xml
  sample-compose/app/src/main/res/navigation/nav_graph_main.xml
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/test/TestModules.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/test/ViewModelExt.kt
  sample-compose/app/src/test/resources/robolectric.properties
  sample-compose/build.gradle.kts
  sample-compose/buildSrc/src/main/java/Configurations.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/detekt-config.yml
  template-compose/detekt-config.yml
Labels: type : feature, status : essential, priority : normal

#375 [#370] [Compose] Migrate to the new permission request logic
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/AndroidManifest.xml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  template-compose/app/build.gradle.kts
  template-compose/buildSrc/src/main/java/Versions.kt
Labels: type : feature, status : essential, priority : high

#381 [Chore] Bump version to 3.16.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore, priority : normal
