Repository nimblehq/android-templates, pull requests merged in 2022-11, with the labels that each got.

#343 [Chore] Update reviewer list
  .github/CODEOWNERS
Labels: type : chore, priority : normal

#344 [#326] [Part 1/2] Add Kover to template
  .cicdtemplate/.bitrise/bitrise.yml
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  Dangerfile
  Gemfile.lock
  scripts/new_project.kts
  template/.gitignore
  template/README.md
  template/app/build.gradle.kts
  template/build.gradle.kts
  template/buildSrc/src/main/java/Versions.kt
  template/buildSrc/src/main/java/plugins/jacoco-report.gradle.kts
  template/data/build.gradle.kts
  template/domain/build.gradle.kts
Labels: type : feature, status : essential, priority : high

#323 [#163][#191][#300] Upgrade JDK, SDK, Gradle & Kotlin
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/verify_newproject_script.yml
  template/app/build.gradle.kts
  template/app/src/main/AndroidManifest.xml
  template/app/src/main/java/co/nimblehq/template/extension/ViewModelExt.kt
  template/build.gradle.kts
  template/buildSrc/src/main/java/Versions.kt
  template/data/build.gradle.kts
  template/data/src/test/java/co/nimblehq/template/data/extensions/ResponseMappingTest.kt
  template/data/src/test/java/co/nimblehq/template/data/repository/RepositoryTest.kt
  template/domain/build.gradle.kts
  template/domain/src/test/java/co/nimblehq/template/domain/usecase/UseCaseTest.kt
  template/gradle/wrapper/gradle-wrapper.properties
Labels: type : chore, status : essential, priority : high

#348 [#346] Fix failing sample xml test
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
Labels: type : bug, status : essential, priority : normal

#345 [#326] [Part 2/2] Add Kover to sample projects
  sample-compose/.gitignore
  sample-compose/README.md
  sample-compose/app/build.gradle.kts
  sample-compose/build.gradle.kts
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/buildSrc/src/main/java/plugins/jacoco-report.gradle.kts
  sample-compose/data/build.gradle.kts
  sample-compose/domain/build.gradle.kts
  sample-xml/.gitignore
  sample-xml/README.md
  sample-xml/app/build.gradle.kts
  sample-xml/build.gradle.kts
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/plugins/jacoco-report.gradle.kts
  sample-xml/data/build.gradle.kts
  sample-xml/domain/build.gradle.kts
Labels: type : feature, status : essential, priority : normal

#347 [#163][#191][#300] Upgrade JDK, SDK, Gradle & Kotlin for Sample
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/AndroidManifest.xml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extension/ViewModelExt.kt
  sample-compose/build.gradle.kts
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/extensions/ResponseMappingTest.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/repository/RepositoryTest.kt
  sample-compose/domain/build.gradle.kts
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
  sample-compose/gradle/wrapper/gradle-wrapper.properties
  sample-xml/app/build.gradle.kts
  sample-xml/app/src/main/AndroidManifest.xml
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/extension/ViewModelExt.kt
  sample-xml/build.gradle.kts
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/data/build.gradle.kts
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/extensions/ResponseMappingTest.kt
  sample-xml/data/src/test/java/co/nimblehq/sample/xml/data/repository/RepositoryTest.kt
  sample-xml/domain/build.gradle.kts
  sample-xml/domain/src/test/java/co/nimblehq/sample/xml/domain/usecase/UseCaseTest.kt
  sample-xml/gradle/wrapper/gradle-wrapper.properties
Labels: type : chore, status : essential, priority : normal

#351 [#335] Remove XML code from Compose template
  template-compose/app/build.gradle.kts
  template-compose/app/src/main/java/co/nimblehq/template/compose/extension/ViewModelExt.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseComposeFragment.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseComposeFragmentCallbacks.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseFragment.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseFragmentCallbacks.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseNavigator.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeFragment.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/xml/HomeFragment.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/xml/HomeViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Color.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Dimension.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Theme.kt
  template-compose/app/src/main/res/layout/fragment_home.xml
  template-compose/app/src/main/res/navigation/nav_graph_main.xml
  template-compose/app/src/main/res/values/dimens.xml
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/BaseFragmentTest.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/xml/HomeFragmentTest.kt
  template-compose/buildSrc/src/main/java/Versions.kt
Labels: type : chore, status : essential, priority : normal

#355 [#334] Remove Compose code from template-xml
  template-xml/app/build.gradle.kts
  template-xml/app/src/main/java/co/nimblehq/template/xml/extension/ViewModelExt.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/base/BaseComposeFragment.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/base/BaseComposeFragmentCallbacks.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/compose/HomeComposeFragment.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/compose/composables/HomeScreen.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/compose/theme/Color.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/compose/theme/Dimension.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/compose/theme/Theme.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/home/HomeFragment.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/home/HomeViewModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/xml/HomeViewModel.kt
  template-xml/app/src/main/res/navigation/nav_graph_main.xml
  template-xml/app/src/test/java/co/nimblehq/template/xml/ui/screens/home/HomeFragmentTest.kt
  template-xml/buildSrc/src/main/java/Versions.kt
Labels: type : chore, status : essential, priority : normal

#356 [#336] [#338] Update new_project.kts to choose between XML or Compose and update documentation
  .github/wiki/Home.md
  .github/workflows/verify_newproject_script.yml
  README.md
  scripts/new_project.kts
Labels: type : feature, status : essential, priority : normal
