Repository nimblehq/android-templates, pull requests merged in 2022-08, with the labels that each got.

#263 [Chore] Bump version to 3.11.0
  template/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#260 [#234] Add help function for kscript
  README.md
  scripts/new_project.kts
Labels: type : feature, status : essential, priority : normal

#276 [#269] Fix file path error when executing new_project.kts
  scripts/new_project.kts
Labels: type : bug, status : essential, priority : high

#278 [#273] Fix incorrect step for running tests in `new_project.kts`
  scripts/new_project.kts
Labels: type : bug, status : essential, priority : high

#277 [#275] Fix references when generating a new project
  scripts/new_project.kts
  template/.gitignore
  template/README.md
Labels: type : bug, status : essential, priority : high

#274 [#242] [Part 2] Create sample folder for Jetpack Compose
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extension/ViewModelExt.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/model/UiModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseComposeFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/NavigationEvent.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/MainNavigator.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeComposeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondFragment.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Color.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Dimension.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Theme.kt
  sample-compose/app/src/main/res/layout/activity_main.xml
  sample-compose/app/src/main/res/navigation/nav_graph_main.xml
  sample-compose/app/src/main/res/values/colors.xml
  sample-compose/app/src/main/res/values/strings.xml
  sample-compose/app/src/main/res/values/styles.xml
  sample-compose/detekt-config.yml
Labels: type : chore, status : essential, priority : high

#286 [#285] Print failed command when execution fails
  scripts/new_project.kts
Labels: type : bug, status : essential, priority : high

#287 [#282] Support running new_project.kts from project root folder
  scripts/new_project.kts
Labels: type : bug, status : essential, priority : high

#290 [#242] Add divider for last item in Compose sample
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
Labels: type : chore, status : essential, priority : high
