Repository nimblehq/android-templates, pull requests merged in 2022-06, with the labels that each got.

#231 [Release] 3.8.0
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  Gemfile.lock
  RxJavaTemplate[DEPRECATED]/buildSrc/src/main/java/Versions.kt
  scripts/new_project.kts
Labels: release

#232 [CHORE] Bump version to 3.9.0
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
Labels: chore

#229 [#210][#211] Update verify script and documentation
  .github/workflows/verify_newproject_script.yml
  README.md
  docs/Home.md
  newproject.sh
  scripts/new_project.kts
Labels: feature

#239 Support light/dark logo on README
  README.md
Labels: bug

#236 [#172] Add section for voting process to Wiki
  docs/Home.md
Labels: chore

#235 [#233] Enable `isMinifyEnabled` for `data`
  CoroutineTemplate/data/build.gradle.kts
Labels: bug

#245 [#100] Add new workflow to generate release note and version tag automatically
  .github/release-drafter-config.yml
  .github/workflows/draft-new-release.yml
  scripts/get_version.kts
Labels: type : chore
