Repository nimblehq/android-templates, pull requests merged in 2022-05, with the labels that each got.

#196 [Chore] Bump version to 3.8.0
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  RxJavaTemplate[DEPRECATED]/buildSrc/src/main/java/Versions.kt
Labels: chore

#215 [#197][#198] Add `new_project.kts` and support arguments
  scripts/new_project.kts
Labels: feature

#216 [#200] Initialize new project directory and copy files recursively
  scripts/new_project.kts
Labels: feature

#218 [#201] Clean project folder
  scripts/new_project.kts
Labels: feature

#219 [#206] Rename package names within files
  scripts/new_project.kts
Labels: feature

#222 [#206] Fix corrupted `debug.keystore` after renaming
  scripts/new_project.kts
Labels: bug

#220 [#202][#203][#204][#205] Rename folder structure for existing modules
  scripts/new_project.kts
Labels: feature

#224 [#209] Build project and run tests
  scripts/new_project.kts
Labels: feature

#225 [#208] Rename application class
  scripts/new_project.kts
Labels: feature

#226 [#199] Show error message for missing/invalid arguments
  scripts/new_project.kts
Labels: feature

#227 [#207] Rename app name in strings.xml
  scripts/new_project.kts
Labels: feature
