Repository nimblehq/android-templates, pull requests merged in 2022-04, with the labels that each got.

#177 [CHORE] Bump version to 3.7.0
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  RxJavaTemplate/buildSrc/src/main/java/Versions.kt
Labels: type : chore

#180 [#179] Fix: incorrect Jacoco coverage report after migrating to Kotlin DSL
  RxJavaTemplate/.gitignore
  RxJavaTemplate/app/.gitignore
  RxJavaTemplate/config/jacoco.gradle.kts
  RxJavaTemplate/data/.gitignore
  RxJavaTemplate/domain/build.gradle.kts
Labels: type : bug

#187 [Chore] Correct project's maintainers info
  .github/CODEOWNERS
Labels: type : chore

#181 [#169] Add Jacoco to CoroutineTemplate
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  CoroutineTemplate/.gitignore
  CoroutineTemplate/README.md
  CoroutineTemplate/app/build.gradle.kts
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  CoroutineTemplate/buildSrc/src/main/java/plugins/jacoco-report.gradle.kts
  CoroutineTemplate/data/build.gradle.kts
  CoroutineTemplate/data/src/test/java/co/nimblehq/coroutine/data/repositoryimpl/UserRepositoryTest.kt
  CoroutineTemplate/domain/build.gradle.kts
  CoroutineTemplate/domain/src/test/java/co/nimblehq/coroutine/domain/usecase/GetUsersUseCaseTest.kt
  Dangerfile
Labels: type : feature

#186 [#184] Add debug keystore for CI
  CoroutineTemplate/.gitignore
  CoroutineTemplate/README.md
  CoroutineTemplate/app/build.gradle.kts
  CoroutineTemplate/config/debug.keystore
  CoroutineTemplate/data/build.gradle.kts
Labels: type : chore

#183 [#168] Fix Detekt for CoroutineTemplate after migrating to DSL
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/NavigatorModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/RepositoryModule.kt
  CoroutineTemplate/build.gradle.kts
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/repository/UserRepositoryImpl.kt
  CoroutineTemplate/data/src/test/java/co/nimblehq/coroutine/data/repository/UserRepositoryTest.kt
Labels: type : bug

#189 [#171] Remove `checkStyle`
  CoroutineTemplate/app/config/checkstyle.xml
  CoroutineTemplate/app/config/xsl/checkstyle-custom.xsl
Labels: type : chore
