Repository nimblehq/android-templates, pull requests merged in 2022-07, with the labels that each got.

#251 [Release] 3.9.0
  .github/release-drafter-config.yml
  .github/workflows/draft-new-release.yml
  .github/workflows/verify_newproject_script.yml
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/OkHttpClientModule.kt
  CoroutineTemplate/buildSrc/src/main/java/Versions.kt
  CoroutineTemplate/data/build.gradle.kts
  README.md
  docs/Home.md
  newproject.sh
  scripts/get_version.kts
  scripts/new_project.kts
Labels: release

#252 [#241] Update kscript for app name argument
  scripts/new_project.kts
Labels: type : feature

#253 [#240] Remove sample code from template folder
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/di/modules/RepositoryModule.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/model/UiModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/model/UserUiModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/ErrorMapping.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/BaseFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/base/NavigationEvent.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/MainNavigator.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/MainViewModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/ComposeFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/ComposeViewModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/HomeComposeFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/HomeComposeViewModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/composables/ComposeScreen.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/composables/ContentCard.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/composables/HomeScreen.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/composables/TitleBar.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/composables/UserItem.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/composables/UserList.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/theme/Color.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/theme/Dimension.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/theme/Shape.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/theme/Theme.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/compose/theme/Typography.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/home/HomeViewModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondBundle.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/second/SecondViewModel.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/xml/HomeFragment.kt
  CoroutineTemplate/app/src/main/java/co/nimblehq/coroutine/ui/screens/xml/HomeViewModel.kt
  CoroutineTemplate/app/src/main/res/font/montserrat_regular.ttf
  CoroutineTemplate/app/src/main/res/layout/fragment_home.xml
  CoroutineTemplate/app/src/main/res/layout/fragment_second.xml
  CoroutineTemplate/app/src/main/res/layout/view_loading.xml
  CoroutineTemplate/app/src/main/res/navigation/nav_graph_main.xml
  CoroutineTemplate/app/src/main/res/values/colors.xml
  CoroutineTemplate/app/src/main/res/values/colors_pallete.xml
  CoroutineTemplate/app/src/main/res/values/dimens.xml
  CoroutineTemplate/app/src/main/res/values/strings.xml
  CoroutineTemplate/app/src/main/res/values/styles.xml
  CoroutineTemplate/app/src/staging/res/values/strings.xml
  CoroutineTemplate/app/src/test/java/co/nimblehq/coroutine/ui/screens/xml/HomeFragmentTest.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/repository/RepositoryImpl.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/repository/UserRepositoryImpl.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/response/Response.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/response/UserResponse.kt
  CoroutineTemplate/data/src/main/java/co/nimblehq/coroutine/data/service/ApiService.kt
  CoroutineTemplate/data/src/test/java/co/nimblehq/coroutine/data/repository/RepositoryTest.kt
  CoroutineTemplate/data/src/test/java/co/nimblehq/coroutine/data/repository/UserRepositoryTest.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/model/Model.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/model/User.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/repository/Repository.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/repository/UserRepository.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/usecase/GetUsersUseCase.kt
  CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/usecase/UseCase.kt
  CoroutineTemplate/domain/src/test/java/co/nimblehq/coroutine/domain/usecase/GetUsersUseCaseTest.kt
  CoroutineTemplate/domain/src/test/java/co/nimblehq/coroutine/domain/usecase/UseCaseTest.kt
  CoroutineTemplate/settings.gradle.kts
Labels: type : chore
