Repository nimblehq/android-templates, pull requests merged in 2023-04, with the labels that each got.

#452 Release/3.18.0
  .github/wiki/Home.md
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  Gemfile.lock
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/PreferencesModule.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/extensions/ResponseMapping.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/di/modules/PreferencesModule.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/extensions/ResponseMapping.kt
  template-compose/app/build.gradle.kts
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/PreferencesModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/extensions/ResponseMapping.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/di/modules/PreferencesModule.kt
  template-xml/data/src/main/java/co/nimblehq/template/xml/data/extensions/ResponseMapping.kt
  version.properties
Labels: type : release, priority : high

#453 [Chore] Bump version to 3.19.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#441 [#425] [Kotlin Flow] Using "launchIn" instead of "collect" for collecting Flows in ViewModel
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdViewModel.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/model/UiModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/base/BaseViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/MainViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/second/SecondViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModelTest.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/model/UiModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/base/BaseViewModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/MainViewModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/home/HomeViewModel.kt
Labels: type : feature
