Repository nimblehq/android-templates, pull requests merged in 2023-05, with the labels that each got.

#449 [#427] [Compose] Defining a "collectAsEffect" extension for Compose to reduce boilerplate code
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extensions/ContextExt.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extensions/FlowExt.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/ErrorMapping.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/common/Toaster.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/extensions/ContextExt.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/extensions/FlowExt.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/ErrorMapping.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/common/Toaster.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
Labels: type : feature

#460 [Release] 3.19.0
  Gemfile.lock
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extensions/ContextExt.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/extensions/FlowExt.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/ErrorMapping.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/common/Toaster.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/second/SecondViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdViewModel.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/model/UiModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/base/BaseViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/MainViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/home/HomeViewModel.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/second/SecondViewModel.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/extensions/ContextExt.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/extensions/FlowExt.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/ErrorMapping.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/common/Toaster.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModelTest.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/model/UiModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/base/BaseViewModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/MainViewModel.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/ui/screens/home/HomeViewModel.kt
  version.properties
Labels: type : release

#450 [#299] [Sample] Add UI tests for XML sample code
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/extension/NavArgsExt.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/second/SecondFragment.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/test/NavArgsExt.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragmentTest.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/second/SecondFragmentTest.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/extension/NavArgsExt.kt
  template-xml/app/src/test/java/co/nimblehq/template/xml/test/NavArgsExt.kt
  template-xml/app/src/test/java/co/nimblehq/template/xml/ui/screens/home/HomeFragmentTest.kt
Labels: type : chore

#456 [#455] Add checkout repository step to the workflow
  .github/workflows/publish_docs_to_wiki.yml
Labels: type : bug

#467 [Chore] Bump version to 3.20.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#466 [#465] [Compose] Optimize to test "SharedFlow" execution in Composable with Robolectric
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/test/CoroutineTestRule.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/BaseScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  template-compose/app/src/test/java/co/nimblehq/template/compose/test/CoroutineTestRule.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/BaseScreenTest.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
Labels: type : feature

#468 [#437] Add red cross emoji to error messages when new_project.kts fails
  scripts/new_project.kts
Labels: type : chore
