Repository nimblehq/android-templates, pull requests merged in 2023-07, with the labels that each got.

#481 [Release] 3.21.0
  .cicdtemplate/.github/README.md
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  README.md
  RxJavaTemplate[DEPRECATED]/fastlane/script/config.rb
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
  sample-compose/app/src/main/res/values/strings.xml
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
  sample-compose/build.gradle.kts
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  scripts/new_project.kts
  template-compose/build.gradle.kts
  version.properties
Labels: type : release

#482 [Chore] Bump version to 3.22.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#486 [#485] Fix repositories import syntax to be in Kotlin format for maven Jitpack
  RxJavaTemplate[DEPRECATED]/build.gradle.kts
  sample-compose/build.gradle.kts
  sample-xml/build.gradle.kts
  template-compose/build.gradle.kts
  template-xml/build.gradle.kts
Labels: type : bug

#483 [#454] Update generating project example script to be in Fenced Code Block
  README.md
Labels: type : chore

#487 [#485] Update import libraries from mavenCentral if possible
  RxJavaTemplate[DEPRECATED]/build.gradle.kts
  sample-compose/build.gradle.kts
  sample-xml/build.gradle.kts
  template-compose/build.gradle.kts
  template-xml/build.gradle.kts
Labels: type : chore

#484 [#448][Part1/2] Initiate codemagic script and implement unit test script for PR and Push event
  codemagic.yaml
Labels: type : feature

#489 [#448] [Part2] sample yaml file for codemagic
  .cicdtemplate/.codemagic/README.md
  .cicdtemplate/.codemagic/codemagic.yaml
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  codemagic.yaml
  template-compose/app/build.gradle.kts
  template-compose/build.gradle.kts
  template-compose/buildSrc/src/main/java/Versions.kt
Labels: type : feature
