Repository nimblehq/android-templates, pull requests merged in 2023-06, with the labels that each got.

#472 [Release] 3.20.0
  .github/workflows/publish_docs_to_wiki.yml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/test/CoroutineTestRule.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/BaseScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/extension/NavArgsExt.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/ui/screens/second/SecondFragment.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/test/NavArgsExt.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/home/HomeFragmentTest.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/second/SecondFragmentTest.kt
  sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  scripts/new_project.kts
  template-compose/app/src/test/java/co/nimblehq/template/compose/test/CoroutineTestRule.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/BaseScreenTest.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
  template-xml/app/src/main/java/co/nimblehq/template/xml/extension/NavArgsExt.kt
  template-xml/app/src/test/java/co/nimblehq/template/xml/test/NavArgsExt.kt
  template-xml/app/src/test/java/co/nimblehq/template/xml/ui/screens/home/HomeFragmentTest.kt
  version.properties
Labels: type : release

#473 [Chore] Bump version to 3.21.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#471 [#464] [Compose] Update Kover's exclusion config
  sample-compose/build.gradle.kts
  template-compose/build.gradle.kts
Labels: type : chore

#475 [#428] [Chore] Update composables to have a Modifier parameter with default value
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
Labels: type : chore

#469 [#433] Remove new project folder if `new_project.kts` fails
  README.md
  scripts/new_project.kts
Labels: type : feature

#478 [#419] [Bug] Prevent the toast for first time app launch from reappearing after navigating back from the second screen
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/main/res/values/strings.xml
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
Labels: type : bug

#477 [#436] Add an argument to specify output folder location to new_project.kts script
  README.md
  scripts/new_project.kts
Labels: type : feature
