Repository nimblehq/android-templates, pull requests merged in 2023-08, with the labels that each got.

#499 [#496] Distribute app without Firebase integration
  .cicdtemplate/.codemagic/codemagic.yaml
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  codemagic.yaml
  template-compose/app/build.gradle.kts
  template-compose/build.gradle.kts
  template-compose/buildSrc/src/main/java/Versions.kt
Labels: type : bug

#497 [Chore] Bump version to 3.23.0
  .github/CODEOWNERS
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#501 [#470] Migrate to Kover 0.7.0
  .cicdtemplate/.bitrise/bitrise.yml
  .cicdtemplate/.codemagic/codemagic.yaml
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  Dangerfile
  codemagic.yaml
  sample-compose/README.md
  sample-compose/app/build.gradle.kts
  sample-compose/build.gradle.kts
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  sample-compose/domain/build.gradle.kts
  sample-xml/README.md
  sample-xml/app/build.gradle.kts
  sample-xml/build.gradle.kts
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/data/build.gradle.kts
  sample-xml/domain/build.gradle.kts
  template-compose/README.md
  template-compose/app/build.gradle.kts
  template-compose/build.gradle.kts
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
  template-compose/domain/build.gradle.kts
  template-xml/README.md
  template-xml/app/build.gradle.kts
  template-xml/build.gradle.kts
  template-xml/buildSrc/src/main/java/Versions.kt
  template-xml/data/build.gradle.kts
  template-xml/domain/build.gradle.kts
Labels: type : chore, priority : normal

#516 [Release] 3.23.0
  .cicdtemplate/.bitrise/bitrise.yml
  .cicdtemplate/.codemagic/codemagic.yaml
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/CODEOWNERS
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  Dangerfile
  codemagic.yaml
  sample-compose/README.md
  sample-compose/app/build.gradle.kts
  sample-compose/build.gradle.kts
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  sample-compose/domain/build.gradle.kts
  sample-xml/README.md
  sample-xml/app/build.gradle.kts
  sample-xml/build.gradle.kts
  sample-xml/buildSrc/src/main/java/Versions.kt
  sample-xml/data/build.gradle.kts
  sample-xml/domain/build.gradle.kts
  template-compose/README.md
  template-compose/app/build.gradle.kts
  template-compose/build.gradle.kts
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
  template-compose/domain/build.gradle.kts
  template-xml/README.md
  template-xml/app/build.gradle.kts
  template-xml/build.gradle.kts
  template-xml/buildSrc/src/main/java/Versions.kt
  template-xml/data/build.gradle.kts
  template-xml/domain/build.gradle.kts
  version.properties
Labels: type : release
