Repository nimblehq/android-templates, pull requests merged in 2023-10, with the labels that each got.

#505 [#512] [KMM Support] Update Kotlin DSL build dependencies & plugins configuration
  template-compose/.gitignore
  template-compose/app/.gitignore
  template-compose/app/build.gradle.kts
  template-compose/build.gradle.kts
  template-compose/buildSrc/.gitignore
  template-compose/buildSrc/src/main/java/BuildTypes.kt
  template-compose/buildSrc/src/main/java/Configurations.kt
  template-compose/buildSrc/src/main/java/Dependencies.kt
  template-compose/buildSrc/src/main/java/Flavors.kt
  template-compose/buildSrc/src/main/java/Modules.kt
  template-compose/buildSrc/src/main/java/Plugins.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
  template-compose/domain/build.gradle.kts
Labels: type : feature

#508 [#513] [KMM Support] Migrate to Gradle 8
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/verify_newproject_script.yml
  scripts/new_project.kts
  template-compose/app/build.gradle.kts
  template-compose/app/src/debug/AndroidManifest.xml
  template-compose/app/src/main/AndroidManifest.xml
  template-compose/app/src/main/res/drawable/ic_launcher_background.xml
  template-compose/app/src/main/res/drawable/ic_launcher_foreground.xml
  template-compose/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  template-compose/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  template-compose/app/src/main/res/mipmap-hdpi/ic_launcher.png
  template-compose/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  template-compose/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  template-compose/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  template-compose/app/src/main/res/mipmap-mdpi/ic_launcher.png
  template-compose/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  template-compose/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  template-compose/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  template-compose/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  template-compose/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  template-compose/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  template-compose/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  template-compose/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  template-compose/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  template-compose/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  template-compose/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  template-compose/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  template-compose/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  template-compose/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  template-compose/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  template-compose/app/src/main/res/values/styles.xml
  template-compose/app/src/main/res/values/themes.xml
  template-compose/app/src/main/res/xml/backup_rules.xml
  template-compose/app/src/main/res/xml/data_extraction_rules.xml
  template-compose/build.gradle.kts
  template-compose/buildSrc/src/main/java/FileExt.kt
  template-compose/buildSrc/src/main/java/Plugins.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
  template-compose/data/consumer-rules.pro
  template-compose/data/proguard-rules.pro
  template-compose/data/src/main/AndroidManifest.xml
  template-compose/domain/build.gradle.kts
  template-compose/gradle.properties
  template-compose/gradle/wrapper/gradle-wrapper.jar
  template-compose/gradle/wrapper/gradle-wrapper.properties
  template-compose/gradlew.bat
  template-compose/settings.gradle.kts
Labels: type : feature

#524 [Chore] Bump version to 3.25.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#532 [#500] The "Checkout" step in "bump_version" workflow does not need to set a custom token
  .cicdtemplate/.github/workflows/bump_version.yml
  .cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/bump_version.yml
  .github/workflows/draft-new-release.yml
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/verify_newproject_script.yml
Labels: type : chore

#537 [#521] Fix: The bump_version template workflow does NOT work
  .cicdtemplate/.github/workflows/bump_version.yml
Labels: type : bug

#527 [#502] Remove Bump version XML step from Bump version workflow
  .github/workflows/bump_version.yml
Labels: type : chore

#510 [#514] [KMM Support] Migrate to Hilt to Koin
  template-compose/app/build.gradle.kts
  template-compose/app/src/main/java/co/nimblehq/template/compose/MainApplication.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/AppModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/MoshiModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/OkHttpClientModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/PreferencesModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/RepositoryModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/RetrofitModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/StorageModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/ViewModelModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/main/MainActivityModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/MainActivity.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
  template-compose/build.gradle.kts
  template-compose/buildSrc/src/main/java/Dependencies.kt
  template-compose/buildSrc/src/main/java/Plugins.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/build.gradle.kts
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/di/Koin.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/di/modules/LocalModule.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/di/modules/RemoteModule.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/di/modules/RepositoryModule.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/repositories/AppPreferencesRepositoryImpl.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/repositories/RepositoryImpl.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/storages/EncryptedSharedPreferences.kt
  template-compose/domain/build.gradle.kts
  template-compose/domain/src/main/java/co/nimblehq/template/compose/domain/di/UseCaseModule.kt
  template-compose/domain/src/main/java/co/nimblehq/template/compose/domain/usecases/UseCase.kt
Labels: type : feature

#544 [#543] Add default spacing definition in app dimensions
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppDimensions.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppDimensions.kt
Labels: type : feature

#545 [#535] Add asStateFlow to the StateFlow variables in ViewModel class
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/base/BaseViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
Labels: type : feature, priority : normal

#546 [#462] Update GitHub workflows to use concurrency
  .cicdtemplate/.github/workflows/bump_version.yml
  .cicdtemplate/.github/workflows/review_pull_request.yml
  .cicdtemplate/.github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/bump_version.yml
  .github/workflows/draft-new-release.yml
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  .github/workflows/verify_newproject_script.yml
Labels: type : chore, priority : normal

#551 [Chore] Bump version to 3.26.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore
