Repository nimblehq/android-templates, pull requests merged in 2023-02, with the labels that each got.

#390 [#377] [Compose] Add a sample to navigate to the ThirdScreen with a custom parcelable data
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppDestination.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppNavigation.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdViewModel.kt
  sample-compose/app/src/main/res/values/strings.xml
  sample-compose/buildSrc/src/main/java/Versions.kt
Labels: type : feature, status : essential, priority : normal

#392 [Release] 3.16.0
  .cicdtemplate/.github/workflows/bump_version.yml
  .github/workflows/bump_version.yml
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppDestination.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/AppNavigation.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/AppBar.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/Item.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/ItemList.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/third/ThirdViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppColors.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppDimensions.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppShapes.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppStyles.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/AppTypography.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Color.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Dimension.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/theme/Theme.kt
  sample-compose/app/src/main/res/values/strings.xml
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  template-compose/app/build.gradle.kts
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppColors.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppDimensions.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppShapes.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppStyles.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppTypography.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Color.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Dimension.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/Theme.kt
  template-compose/app/src/main/res/values/colors.xml
  template-compose/app/src/main/res/values/styles.xml
  template-compose/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : release

#395 [Chore] Bump version to 3.17.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#400 [#394] Fix bump version workflow
  .github/workflows/bump_version.yml
Labels: type : bug, priority : normal

#404 [#379] Update issue templates to automatically included the correct labels
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
Labels: type : chore

#384 [#354] [Compose] 1/2: Setup UI and Integration tests
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/test/TestDispatchersProvider.kt
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/model/UiModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/test/CoroutineTestRule.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/src/test/java/co/nimblehq/sample/compose/data/repository/RepositoryTest.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UseCaseTest.kt
  template-compose/app/build.gradle.kts
  template-compose/app/src/androidTest/java/co/nimblehq/template/compose/ui/screens/home/HomeScreenTest.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/model/UiModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModel.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/theme/AppShapes.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/test/CoroutineTestRule.kt
  template-compose/app/src/test/java/co/nimblehq/template/compose/ui/screens/home/HomeViewModelTest.kt
  template-compose/buildSrc/src/main/java/Versions.kt
  template-compose/data/src/test/java/co/nimblehq/template/compose/data/repository/RepositoryTest.kt
  template-compose/domain/src/test/java/co/nimblehq/template/compose/domain/usecase/UseCaseTest.kt
Labels: type : feature, priority : normal

#389 [#159][Part1] [Compose] Support datastore replacing shared preference
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/AndroidManifest.xml
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/PreferencesModule.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/StorageModule.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/base/BaseViewModel.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModel.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-compose/data/build.gradle.kts
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/repository/AppPreferencesRepositoryImpl.kt
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/storage/NormalSharedPreferences.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/repository/AppPreferencesRepository.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/GetModelsUseCase.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/IsFirstTimeLaunchPreferencesUseCase.kt
  sample-compose/domain/src/main/java/co/nimblehq/sample/compose/domain/usecase/UpdateFirstTimeLaunchPreferencesUseCase.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/GetModelsUseCaseTest.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/IsFirstTimeLaunchPreferencesUseCaseTest.kt
  sample-compose/domain/src/test/java/co/nimblehq/sample/compose/domain/usecase/UpdateFirstTimeLaunchPreferencesUseCaseTest.kt
Labels: type : feature, priority : normal

#412 [Chore] Update code owners
  .github/CODEOWNERS
Labels: type : chore, priority : low

#411 [#297] Update release-template description
  .github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
Labels: type : chore, priority : low
