Repository nimblehq/android-templates, pull requests merged in 2023-03, with the labels that each got.

#421 [Chore] Bump version to 3.18.0
  sample-compose/buildSrc/src/main/java/Versions.kt
  sample-xml/buildSrc/src/main/java/Versions.kt
  version.properties
Labels: type : chore

#422 [#410] Update collectAsState to collectAsStateWithLifecyle for observing flow in Android lifecycle manner
  sample-compose/app/build.gradle.kts
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt
  sample-compose/buildSrc/src/main/java/Versions.kt
  template-compose/app/build.gradle.kts
  template-compose/app/src/main/java/co/nimblehq/template/compose/ui/screens/home/HomeScreen.kt
  template-compose/buildSrc/src/main/java/Versions.kt
Labels: type : feature, priority : normal

#430 [#415] [Chore] Update dependency injection implementation for the DataStore from the delegate pattern to the builder pattern
  sample-compose/app/src/main/java/co/nimblehq/sample/compose/di/modules/PreferencesModule.kt
  sample-xml/app/src/main/java/co/nimblehq/sample/xml/di/modules/PreferencesModule.kt
  template-compose/app/src/main/java/co/nimblehq/template/compose/di/modules/PreferencesModule.kt
  template-xml/app/src/main/java/co/nimblehq/template/xml/di/modules/PreferencesModule.kt
Labels: type : chore, priority : normal

#435 [#426] [Kotlin Flow] Refactor `try/catch` to `runCatching { ... }`
  sample-compose/data/src/main/java/co/nimblehq/sample/compose/data/extensions/ResponseMapping.kt
  sample-xml/data/src/main/java/co/nimblehq/sample/xml/data/extensions/ResponseMapping.kt
  template-compose/data/src/main/java/co/nimblehq/template/compose/data/extensions/ResponseMapping.kt
  template-xml/data/src/main/java/co/nimblehq/template/xml/data/extensions/ResponseMapping.kt
Labels: type : chore, priority : normal

#444 [#443] Fix: Missing additional use-cases mocking and tests verifying steps in CI for sample-xml & sample-compose
  .github/workflows/review_pull_request.yml
  .github/workflows/run_detekt_and_unit_tests.yml
  sample-compose/app/src/androidTest/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreenTest.kt
  sample-compose/app/src/test/java/co/nimblehq/sample/compose/ui/screens/home/HomeViewModelTest.kt
Labels: type : feature

#409 [#378] Update Wiki to remove optional features and clarify voting labels
  .github/wiki/Home.md
Labels: type : chore, priority : normal
